dart-lang/dart-vim-plugin

ftplugin/dart.vim

Allows better formatting for triple dash doc style comments

Add triple dash to the list of comment formats

---

syntax/dart.vim

Add `enum` keyword, fix syntax for `import` and `export` statements, move
`factory` to storage class for consistency, and highlight @metadata
annotations.

Syntax highlighting: metadata and more keywords.

---

indent/dart.vim

Final indentation should be handled by dartfmt, but having vim behave
slightly closer to dartfmt while editing gives a less annoying
experience.
- Add a DartIndent function to handle edge cases not covered by cindent
- Check whether previous line starts with '@' and don't indent
- Check wither previous line opens a List literal and indent

Tweak indentation after annotation and inside List

---

autoload/dart.vim

Fixes #36
Pipe the current contents of the buffer to stdin on the dartfmt call
rather than have it read the file from disk.
Also improve error parsing:
- Strip the first 2 lines of the stderr output
- Prependg the buffer file path to every line, since the output now
contains 'stdin' instead of an actual file path
- Use a multiline errorformat string so that it drops the code and
pointer lines leaving only the error message

Format buffer contents instead of from disk

---

autoload/dart.vim
ftplugin/dart.vim

Add an includeexpr to a function that can parse .packages file and
resolve the absolute file path to a package: uri. If fname does not
include 'package:' it is returned directly so relative paths still work
as before.
Finds and parses the .packages file on every call. This is fast enough
that caching (and therefore needing to invalidate) the map is probably
not worthwhile.

Support gf for package: uris when .packages exists

---

README.md

As someone who has never used Pathogen, although it was clear to see I needed Pathogen, I was not sure how to tie them together.  I think this change makes it more clear and should get users up and running with less confusion.

Specify pathogen.

---

README.md

Fixes #41 
Indicate that any typical install approach will work - we don't require
pathogen.
- Show examples for vim-plug, vundle, and pathogen
- Move the install instructions to the end of the README
- Clean up some link references to use the link text and to sit under
the section where the link is used

More general install instructions

---

autoload/dart.vim

- Using `setline` instead of `delete` and `put` lets marks like the
changelist survive the edit without being invalidated and won't
cause other windows showing the buffer to jump.
- keepjumps prevents the edit from adding a changelist entry at the
beginning of the file.

Allow formatting without impacting changelist

---

syntax/dart.vim

Prevents a missing quote from changing highlighting through the rest of
the file - less disruptive in the middle of a change.

Add `oneline` to dartString highlighting

---

syntax/dart.vim

When using `dart_html_in_strings` an html region can open inside a
string and not close which prevents the overall syntax from resetting at
the end of the string. Adding `keepend` prevents this problem.
Explicitly allow ignoring quotes inside string interpolation, or escaped
with slash, by adding `extend` to those contained matches.

Prevent String highlighting from leaking

---

README.md
syntax/dart.vim

The HTML syntax file changes the `case` option which causes the core
library keywords to get hilighted without case sensitivity.
- Explicitly set `syntax case match` for clarity
- Move all the keywork matches above the String hilighting where we may
clobber settings due to the HTML syntax loading
Also add an option to disable corelib higlighting to close TODO

Fix keyword matches when using HTML in strings

---

syntax/dart.vim

Note that the 'native' keyword is not part of the Dart Language
Specification. It is, however, used by Dart core library developers and
those using the Dart VM embedding API in order to implement dart:
extension libraries (e.g., Flutter).

Highlight the native keyword

---

syntax/dart.vim

Adds syntax highlighting for the 'covariant' keyword, which can be used
in formal parameter lists and on non-final fields.

Add covariant keyword

---

.gitignore
doc/dart.txt

Makes `:help dart` do something useful.

Add some docs

---

syntax/dart.vim

Current syntax highlighting is not coloring the shebang line properly:
```
#!/usr/bin/dart
```
Added a change that would paint the first line as a comment if it starts with "#!".

Added syntax highlighting for the shebang line

---

syntax/dart.vim

Similar to #48 this prevents regions which start inside a multiline
string from leaking past the end of the string.

Add keepend for multiline strings

---

autoload/dart.vim
plugin/dart.vim

Dart doesn't expose capabilities to set file permissions so files
downloaded by pub are not readonly. After opening a file, if it's in the
pub cache set `nomodifiable` to prevent accidental edits.

Prevent writes to files in the pub cache

---

README.md

Inform users that they have to run `PlugInstall` once they have updated their `.vimrc`.

Inform users that they have to run `PlugInstall`.

---

autoload/dart.vim

Prevents vim from thinking the file is modified and needs to be saved
after a format which doesn't change anything.
The `[:-2]` is because the `dartfmt` output includes a trailing newline
while the `join` omits it.

Avoid changes if the buffer is already formatted

---

syntax/dart.vim

It can be used in the places where there used to be `class`.

Add highlighting for mixin keyword

---

README.md

Closes #79
Removes mention of `dart_language_server` since the analysis server is
the supported path expect to use and promote going forward. Adds an FAQ
entry which describes the command that needs to be run to start the
analysis server since it's not as simple as a single command already on
your `$PATH`. Also points out the option of using a preconfigured plugin
which handles locating the right command for you.

Add an FAQ entry for using Dart analysis server

---

autoload/dart.vim

At some point the output from dartfmt changed from `stdin` to `<stdin>`
and broke the error format. Update to use `--stdin-name` argument rather
than the hacky approach of prefixing the name to all lines ourselves.
This option has existed since https://github.com/dart-lang/dart_style/pull/740

Fix error parsing from dartfmt

---

autoload/dart.vim

Closes #67 
After fixing syntax errors surfaced by a format, and then running a
successful format, clear out the quickfix list and close it. This is a
nicer UX than needing to `:cclose` manually.
- Add a 'reason' field in the 'context' for the quickfix list whenever
we set it.
- After a successful format, check if the quickfix is set for the
'dartfmt' reason, and if it is close and clear it.

Automatically clear and close quickfix list

---

README.md
syntax/dart.vim

Hello!
I start to write Flutter with Vim recently. 
I just found out this [issue ](https://github.com/dart-lang/dart-vim-plugin/issues/74)when I want my defined types to be highlighted .
I added highlight options `dart_highlight_types`. default is false.
Thank you!

Add highlighting for user defined types (#74)

---

ftdetect/dart.vim

The `did_filetype()` check will avoid doing any work if the filetype was
chosen somewhere else.
Use only `BufRead` since `BufNewFile` shouldn't have any content.

Add filetype detection for shebang lines

---

autoload/dart.vim

The first time `dartfmt` is run after upgrading the Dart SDK the message
'Isolate creation failed' is emitted on stderr. We can't ignore stderr
completely since we also get errors there if the code can't be
formatted.
See https://github.com/dart-lang/sdk/issues/38507
- Use `systemlist` to avoid an extra split of the string to check the
last line, keep `buffer_content` as a list as well.
- If the last line matches exactly the error message, remove and ignore
it.

Handle 'Isolate creation failed' in dartfmt

---

ftplugin/dart.vim
syntax/dart.vim

Add `$` as a keyword character since it is allowed in Dart identifiers.
This fixes the behavior of  the `w` word motion as well as allows syntax
groups to match across the character.
Refactor the `dartTypeName` regex. Use an optional `_` at the beginning,
rather than repeating the pattern with an without `_`. Use the `\u`
character class instead of the group `[A-Z]`. Replace the `\w` character
class with a group that includes the same characters and adds `$`.

Allow $ character in type names

---

syntax/dart.vim

Personally, I think "keyword" suits `var` better than "type," but if that isn't a welcome change I can remove it.
Also, the default for `g:dart_highlight_functions` is `v:true`; let me know if it should default to `v:false`.
Function highlighting code gotten from [this gist](https://gist.github.com/sgon00/3e6636f7cafcecb7ed88df9169d8229c#file-dart-vim-L1-L2).

Add function highlighting

---

README.md
doc/dart.txt
syntax/dart.vim

Closes #95
Keep the `dart_html_in_strings` variable since it has behavior that
can't be changed with highlight groups.
Remove the `dart_highlight_types` and `dart_corelib_highlight`
variables. The behavior from setting these can be achieved by linking
specific highlight groups to `Normal`.
Move the lowercase "primitive" type names from `dartCoreType` to
`dartSdkClass` since they fit better alongside `String`. The ones
remaining in `dartCoreType` are still a "type", or at least often used
in a similar way, but have no class definition. When we add `Never` it
will be a `dartCoreType`.
Add a doc section that describes the highlight groups that are most
likely to be configured with an example of how to disable them.
Rename some groups from "core" to "sdk" since they are more broad than
the …

Remove configuration variables for highlights

---

syntax/dart.vim

The extension keyword was added in Dart 2.7.
https://dart.dev/guides/language/extension-methods

Add extension to type keywords list

---

autoload/dart.vim
ftdetect/dart.vim
indent/dart.vim
plugin/dart.vim
syntax/dart.vim

Fixes violations of the Google vimscipt style guide.
- Use string matching operators that don't depend on user settings.
- Always put autocmd in an augroup.
- Use single quotes.
- Always prefix variables with their scope.

Fix lints from vim-vint

---

syntax/dart.vim

Fixes #103
Everything up to a `;` is part of a directive, including newlines. Add
`skipnl` so these newlines don't cause the combinators to highlight as
normal code.
Also add `dartComment` and `dartLineComment` to the `contains` for
`dartCombinators`.

Add skipnl to match import URI and combinators

---

syntax/dart.vim

These two keywords are each introduced with the new Null Safety language feature.

Add 'late' and 'required' keywords

---

README.md
autoload/dart.vim
doc/dart.txt
plugin/dart.vim

With this PR, users will be able to configure DartFmt options with `g:dartfmt_options`. They can change the default line limit from 80 to any number they prefer. They can also make `dartfmt` fix issues such as optional `new` keywords.
```
$ dartfmt -h
...
Non-whitespace fixes (off by default):
--fix                              Apply all style fixes.
--fix-doc-comments                 Use triple slash for documentation comments.
--fix-function-typedefs            Use new syntax for function type typedefs.
--fix-named-default-separator      Use "=" as the separator before named parameter default values.
--fix-optional-const               Remove "const" keyword inside constant context.
--fix-optional-new                 Remove "new" keyword.
--fix-single-cascade-statements    Remove …
```

Enable DartFmt Options with g:dartfmt_options

---

syntax/dart.vim

I translated the regex used by the VsCode dart plugin for the function match which fixes dart-lang#105
Also fixed an issue where you where only allowed to have a single underscore and no dollar sign before the first uppercase letter of a user type or before the first lowercase letter of a function

Fix function and usertype matching

---

doc/dart.txt

Closes #119
This allows running `:help g:dartfmt_options` to find the docs and links
to the docs for the variable from the docs for the `:DartFmt` command.

Add a help tag for g:dartfmt_options

---

autoload/dart.vim
doc/dart.txt

Move from dartfmt to dart format

---

doc/dart.txt

Closes #131
Remove the docs for `:Dart2JS` and `:DartAnalyzer` which are no longer
functional.
Add docs for the format on save related command and configuration.

Clean up some stale docs

---

autoload/dart.vim
plugin/dart.vim

The implementations of these commands were dropped 2 years ago and we
left in stubs to avoid confusion for users still trying trying to use
them. We have not had complains and it's unlikely these stubs are
invoked anymore.

Drop DartAnalyzer and Dart2JS command stubs

---

README.md
doc/dart.txt
indent/dart.vim

Closes #114
We've gotten a few requests to change the default indentation of
argument lists since it's so common for flutter authors to use frequent
trailing commas and see the different indentation behavior after
formatting. Add a configuration option so users who mostly have trailing
commas in argument lists can have their more common indentation while
typing as well.

Add g:dart_trailing_comma_indent

---

syntax/dart.vim

This PR adds the new `when` keyword
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a …

Add `when` keyword

---

syntax/dart.vim

Missing highlights for classes.
https://github.com/dart-lang/dart-syntax-highlight/blob/master/test/test_files/classes.dart
I'm not sure if `dartStorageClass` is the correct group for these keywords.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#maki …

Add missing class modifier keywords
